# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: about_service.proto for package 'protolca.services'

require 'grpc'
require 'about_service_pb'

module Protolca
  module Services
    module AboutService
      # This service gives some general information of the service
      # interface.
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'protolca.services.AboutService'

        rpc :About, ::Google::Protobuf::Empty, ::Protolca::Services::AboutResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
