# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: about_service.proto

require 'google/protobuf/empty_pb'
require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("about_service.proto", :syntax => :proto3) do
    add_message "protolca.services.AboutResponse" do
      optional :database, :string, 1
      optional :version, :int32, 2
      optional :min_supported_version, :int32, 3
    end
  end
end

module Protolca
  module Services
    AboutResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.services.AboutResponse").msgclass
  end
end
