# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow_map_service.proto

require 'olca_pb'
require 'google/protobuf/empty_pb'
require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("flow_map_service.proto", :syntax => :proto3) do
    add_message "protolca.services.ProtoFlowMapName" do
      optional :name, :string, 1
    end
  end
end

module Protolca
  module Services
    ProtoFlowMapName = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.services.ProtoFlowMapName").msgclass
  end
end
