# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: olca.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("olca.proto", :syntax => :proto3) do
    add_message "protolca.ProtoActor" do
      optional :id, :string, 1, json_name: "@id"
      optional :name, :string, 2
      optional :description, :string, 3
      optional :version, :string, 4
      optional :last_change, :string, 5
      optional :type, :enum, 6, "protolca.ProtoType", json_name: "@type"
      optional :category, :message, 7, "protolca.ProtoRef"
      repeated :tags, :string, 8
      optional :library, :string, 9
      optional :address, :string, 10
      optional :city, :string, 11
      optional :country, :string, 12
      optional :email, :string, 13
      optional :telefax, :string, 14
      optional :telephone, :string, 15
      optional :website, :string, 16
      optional :zip_code, :string, 17
    end
    add_message "protolca.ProtoAllocationFactor" do
      optional :allocation_type, :enum, 1, "protolca.ProtoAllocationType"
      optional :product, :message, 2, "protolca.ProtoRef"
      optional :value, :double, 3
      optional :formula, :string, 4
      optional :exchange, :message, 5, "protolca.ProtoExchangeRef"
    end
    add_message "protolca.ProtoCalculationSetup" do
      optional :calculation_type, :enum, 1, "protolca.ProtoCalculationType"
      optional :product_system, :message, 2, "protolca.ProtoRef"
      optional :process, :message, 3, "protolca.ProtoRef"
      optional :impact_method, :message, 4, "protolca.ProtoRef"
      optional :nw_set, :message, 5, "protolca.ProtoRef"
      repeated :parameters, :message, 6, "protolca.ProtoParameterRedef"
      optional :allocation, :enum, 7, "protolca.ProtoAllocationType"
      optional :with_costs, :bool, 8
      optional :with_regionalization, :bool, 9
      optional :unit, :message, 10, "protolca.ProtoRef"
      optional :amount, :double, 11
      optional :flow_property, :message, 12, "protolca.ProtoRef"
      optional :number_of_runs, :int32, 13
    end
    add_message "protolca.ProtoCategory" do
      optional :id, :string, 1, json_name: "@id"
      optional :name, :string, 2
      optional :description, :string, 3
      optional :version, :string, 4
      optional :last_change, :string, 5
      optional :type, :enum, 6, "protolca.ProtoType", json_name: "@type"
      optional :category, :message, 7, "protolca.ProtoRef"
      repeated :tags, :string, 8
      optional :library, :string, 9
      optional :model_type, :enum, 10, "protolca.ProtoCategoryType"
    end
    add_message "protolca.ProtoCurrency" do
      optional :id, :string, 1, json_name: "@id"
      optional :name, :string, 2
      optional :description, :string, 3
      optional :version, :string, 4
      optional :last_change, :string, 5
      optional :type, :enum, 6, "protolca.ProtoType", json_name: "@type"
      optional :category, :message, 7, "protolca.ProtoRef"
      repeated :tags, :string, 8
      optional :library, :string, 9
      optional :code, :string, 10
      optional :conversion_factor, :double, 11
      optional :reference_currency, :message, 12, "protolca.ProtoRef"
    end
    add_message "protolca.ProtoDQIndicator" do
      optional :name, :string, 1
      optional :position, :int32, 2
      repeated :scores, :message, 3, "protolca.ProtoDQScore"
    end
    add_message "protolca.ProtoDQScore" do
      optional :position, :int32, 1
      optional :label, :string, 2
      optional :description, :string, 3
      optional :uncertainty, :double, 4
    end
    add_message "protolca.ProtoDQSystem" do
      optional :id, :string, 1, json_name: "@id"
      optional :name, :string, 2
      optional :description, :string, 3
      optional :version, :string, 4
      optional :last_change, :string, 5
      optional :type, :enum, 6, "protolca.ProtoType", json_name: "@type"
      optional :category, :message, 7, "protolca.ProtoRef"
      repeated :tags, :string, 8
      optional :library, :string, 9
      optional :has_uncertainties, :bool, 10
      optional :source, :message, 11, "protolca.ProtoRef"
      repeated :indicators, :message, 12, "protolca.ProtoDQIndicator"
    end
    add_message "protolca.ProtoExchange" do
      optional :avoided_product, :bool, 1
      optional :cost_formula, :string, 2
      optional :cost_value, :double, 3
      optional :currency, :message, 4, "protolca.ProtoRef"
      optional :internal_id, :int32, 5
      optional :flow, :message, 6, "protolca.ProtoRef"
      optional :flow_property, :message, 7, "protolca.ProtoRef"
      optional :input, :bool, 8
      optional :quantitative_reference, :bool, 9
      optional :base_uncertainty, :double, 10
      optional :default_provider, :message, 11, "protolca.ProtoRef"
      optional :amount, :double, 12
      optional :amount_formula, :string, 13
      optional :unit, :message, 14, "protolca.ProtoRef"
      optional :dq_entry, :string, 15
      optional :uncertainty, :message, 16, "protolca.ProtoUncertainty"
      optional :description, :string, 17
    end
    add_message "protolca.ProtoExchangeRef" do
      optional :internal_id, :int32, 1
    end
    add_message "protolca.ProtoFlow" do
      optional :id, :string, 1, json_name: "@id"
      optional :name, :string, 2
      optional :description, :string, 3
      optional :version, :string, 4
      optional :last_change, :string, 5
      optional :type, :enum, 6, "protolca.ProtoType", json_name: "@type"
      optional :category, :message, 7, "protolca.ProtoRef"
      repeated :tags, :string, 8
      optional :library, :string, 9
      optional :flow_type, :enum, 10, "protolca.ProtoFlowType"
      optional :cas, :string, 11
      optional :formula, :string, 12
      repeated :flow_properties, :message, 13, "protolca.ProtoFlowPropertyFactor"
      optional :location, :message, 14, "protolca.ProtoRef"
      optional :synonyms, :string, 15
      optional :infrastructure_flow, :bool, 16
    end
    add_message "protolca.ProtoFlowMap" do
      optional :id, :string, 1, json_name: "@id"
      optional :name, :string, 2
      optional :description, :string, 3
      optional :version, :string, 4
      optional :last_change, :string, 5
      optional :source, :message, 6, "protolca.ProtoRef"
      optional :target, :message, 7, "protolca.ProtoRef"
      repeated :mappings, :message, 8, "protolca.ProtoFlowMapEntry"
    end
    add_message "protolca.ProtoFlowMapEntry" do
      optional :from, :message, 1, "protolca.ProtoFlowMapRef"
      optional :to, :message, 2, "protolca.ProtoFlowMapRef"
      optional :conversion_factor, :double, 3
    end
    add_message "protolca.ProtoFlowMapRef" do
      optional :flow, :message, 1, "protolca.ProtoRef"
      optional :flow_property, :message, 2, "protolca.ProtoRef"
      optional :unit, :message, 3, "protolca.ProtoRef"
      optional :provider, :message, 4, "protolca.ProtoRef"
    end
    add_message "protolca.ProtoFlowProperty" do
      optional :id, :string, 1, json_name: "@id"
      optional :name, :string, 2
      optional :description, :string, 3
      optional :version, :string, 4
      optional :last_change, :string, 5
      optional :type, :enum, 6, "protolca.ProtoType", json_name: "@type"
      optional :category, :message, 7, "protolca.ProtoRef"
      repeated :tags, :string, 8
      optional :library, :string, 9
      optional :flow_property_type, :enum, 10, "protolca.ProtoFlowPropertyType"
      optional :unit_group, :message, 11, "protolca.ProtoRef"
    end
    add_message "protolca.ProtoFlowPropertyFactor" do
      optional :flow_property, :message, 1, "protolca.ProtoRef"
      optional :conversion_factor, :double, 2
      optional :reference_flow_property, :bool, 3
    end
    add_message "protolca.ProtoFlowResult" do
      optional :flow, :message, 1, "protolca.ProtoRef"
      optional :input, :bool, 2
      optional :value, :double, 3
      optional :location, :message, 4, "protolca.ProtoRef"
    end
    add_message "protolca.ProtoImpactCategory" do
      optional :id, :string, 1, json_name: "@id"
      optional :name, :string, 2
      optional :description, :string, 3
      optional :version, :string, 4
      optional :last_change, :string, 5
      optional :type, :enum, 6, "protolca.ProtoType", json_name: "@type"
      optional :category, :message, 7, "protolca.ProtoRef"
      repeated :tags, :string, 8
      optional :library, :string, 9
      optional :reference_unit_name, :string, 10
      repeated :parameters, :message, 11, "protolca.ProtoParameter"
      repeated :impact_factors, :message, 12, "protolca.ProtoImpactFactor"
    end
    add_message "protolca.ProtoImpactFactor" do
      optional :flow, :message, 1, "protolca.ProtoRef"
      optional :location, :message, 2, "protolca.ProtoRef"
      optional :flow_property, :message, 3, "protolca.ProtoRef"
      optional :unit, :message, 4, "protolca.ProtoRef"
      optional :value, :double, 5
      optional :formula, :string, 6
      optional :uncertainty, :message, 7, "protolca.ProtoUncertainty"
    end
    add_message "protolca.ProtoImpactMethod" do
      optional :id, :string, 1, json_name: "@id"
      optional :name, :string, 2
      optional :description, :string, 3
      optional :version, :string, 4
      optional :last_change, :string, 5
      optional :type, :enum, 6, "protolca.ProtoType", json_name: "@type"
      optional :category, :message, 7, "protolca.ProtoRef"
      repeated :tags, :string, 8
      optional :library, :string, 9
      repeated :impact_categories, :message, 10, "protolca.ProtoRef"
      repeated :nw_sets, :message, 11, "protolca.ProtoNwSet"
    end
    add_message "protolca.ProtoImpactResult" do
      optional :impact_category, :message, 1, "protolca.ProtoRef"
      optional :value, :double, 2
    end
    add_message "protolca.ProtoLocation" do
      optional :id, :string, 1, json_name: "@id"
      optional :name, :string, 2
      optional :description, :string, 3
      optional :version, :string, 4
      optional :last_change, :string, 5
      optional :type, :enum, 6, "protolca.ProtoType", json_name: "@type"
      optional :category, :message, 7, "protolca.ProtoRef"
      repeated :tags, :string, 8
      optional :library, :string, 9
      optional :code, :string, 10
      optional :latitude, :double, 11
      optional :longitude, :double, 12
      optional :geometry_bytes, :bytes, 13
    end
    add_message "protolca.ProtoNwFactor" do
      optional :impact_category, :message, 1, "protolca.ProtoRef"
      optional :normalisation_factor, :double, 2
      optional :weighting_factor, :double, 3
    end
    add_message "protolca.ProtoNwSet" do
      optional :id, :string, 1, json_name: "@id"
      optional :name, :string, 2
      optional :description, :string, 3
      optional :version, :string, 4
      optional :last_change, :string, 5
      optional :weighted_score_unit, :string, 6
      repeated :factors, :message, 7, "protolca.ProtoNwFactor"
    end
    add_message "protolca.ProtoParameter" do
      optional :id, :string, 1, json_name: "@id"
      optional :name, :string, 2
      optional :description, :string, 3
      optional :version, :string, 4
      optional :last_change, :string, 5
      optional :type, :enum, 6, "protolca.ProtoType", json_name: "@type"
      optional :category, :message, 7, "protolca.ProtoRef"
      repeated :tags, :string, 8
      optional :library, :string, 9
      optional :parameter_scope, :enum, 10, "protolca.ProtoParameterScope"
      optional :input_parameter, :bool, 11
      optional :value, :double, 12
      optional :formula, :string, 13
      optional :uncertainty, :message, 14, "protolca.ProtoUncertainty"
    end
    add_message "protolca.ProtoParameterRedef" do
      optional :context, :message, 1, "protolca.ProtoRef"
      optional :description, :string, 2
      optional :name, :string, 3
      optional :uncertainty, :message, 4, "protolca.ProtoUncertainty"
      optional :value, :double, 5
    end
    add_message "protolca.ProtoParameterRedefSet" do
      optional :name, :string, 1
      optional :description, :string, 2
      optional :is_baseline, :bool, 3
      repeated :parameters, :message, 4, "protolca.ProtoParameterRedef"
    end
    add_message "protolca.ProtoProcess" do
      optional :id, :string, 1, json_name: "@id"
      optional :name, :string, 2
      optional :description, :string, 3
      optional :version, :string, 4
      optional :last_change, :string, 5
      optional :type, :enum, 6, "protolca.ProtoType", json_name: "@type"
      optional :category, :message, 7, "protolca.ProtoRef"
      repeated :tags, :string, 8
      optional :library, :string, 9
      repeated :allocation_factors, :message, 10, "protolca.ProtoAllocationFactor"
      optional :default_allocation_method, :enum, 11, "protolca.ProtoAllocationType"
      repeated :exchanges, :message, 12, "protolca.ProtoExchange"
      optional :last_internal_id, :int32, 13
      optional :location, :message, 14, "protolca.ProtoRef"
      repeated :parameters, :message, 15, "protolca.ProtoParameter"
      optional :process_documentation, :message, 16, "protolca.ProtoProcessDocumentation"
      optional :process_type, :enum, 17, "protolca.ProtoProcessType"
      optional :dq_system, :message, 18, "protolca.ProtoRef"
      optional :exchange_dq_system, :message, 19, "protolca.ProtoRef"
      optional :social_dq_system, :message, 20, "protolca.ProtoRef"
      optional :dq_entry, :string, 21
      optional :infrastructure_process, :bool, 22
      repeated :social_aspects, :message, 23, "protolca.ProtoSocialAspect"
    end
    add_message "protolca.ProtoProcessDocumentation" do
      optional :time_description, :string, 1
      optional :valid_until, :string, 2
      optional :valid_from, :string, 3
      optional :technology_description, :string, 4
      optional :data_collection_description, :string, 5
      optional :completeness_description, :string, 6
      optional :data_selection_description, :string, 7
      optional :review_details, :string, 8
      optional :data_treatment_description, :string, 9
      optional :inventory_method_description, :string, 10
      optional :modeling_constants_description, :string, 11
      optional :reviewer, :message, 12, "protolca.ProtoRef"
      optional :sampling_description, :string, 13
      repeated :sources, :message, 14, "protolca.ProtoRef"
      optional :restrictions_description, :string, 15
      optional :copyright, :bool, 16
      optional :creation_date, :string, 17
      optional :data_documentor, :message, 18, "protolca.ProtoRef"
      optional :data_generator, :message, 19, "protolca.ProtoRef"
      optional :data_set_owner, :message, 20, "protolca.ProtoRef"
      optional :intended_application, :string, 21
      optional :project_description, :string, 22
      optional :publication, :message, 23, "protolca.ProtoRef"
      optional :geography_description, :string, 24
    end
    add_message "protolca.ProtoProcessLink" do
      optional :provider, :message, 1, "protolca.ProtoRef"
      optional :flow, :message, 2, "protolca.ProtoRef"
      optional :process, :message, 3, "protolca.ProtoRef"
      optional :exchange, :message, 4, "protolca.ProtoExchangeRef"
    end
    add_message "protolca.ProtoProductSystem" do
      optional :id, :string, 1, json_name: "@id"
      optional :name, :string, 2
      optional :description, :string, 3
      optional :version, :string, 4
      optional :last_change, :string, 5
      optional :type, :enum, 6, "protolca.ProtoType", json_name: "@type"
      optional :category, :message, 7, "protolca.ProtoRef"
      repeated :tags, :string, 8
      optional :library, :string, 9
      repeated :processes, :message, 10, "protolca.ProtoRef"
      optional :reference_process, :message, 11, "protolca.ProtoRef"
      optional :reference_exchange, :message, 12, "protolca.ProtoExchangeRef"
      optional :target_amount, :double, 13
      optional :target_unit, :message, 14, "protolca.ProtoRef"
      optional :target_flow_property, :message, 15, "protolca.ProtoRef"
      repeated :process_links, :message, 16, "protolca.ProtoProcessLink"
      repeated :parameter_sets, :message, 17, "protolca.ProtoParameterRedefSet"
    end
    add_message "protolca.ProtoProject" do
      optional :id, :string, 1, json_name: "@id"
      optional :name, :string, 2
      optional :description, :string, 3
      optional :version, :string, 4
      optional :last_change, :string, 5
      optional :type, :enum, 6, "protolca.ProtoType", json_name: "@type"
      optional :category, :message, 7, "protolca.ProtoRef"
      repeated :tags, :string, 8
      optional :library, :string, 9
      optional :impact_method, :message, 10, "protolca.ProtoRef"
      optional :nw_set, :message, 11, "protolca.ProtoNwSet"
    end
    add_message "protolca.ProtoRef" do
      optional :id, :string, 1, json_name: "@id"
      optional :name, :string, 2
      optional :description, :string, 3
      optional :version, :string, 4
      optional :last_change, :string, 5
      optional :type, :enum, 6, "protolca.ProtoType", json_name: "@type"
      repeated :category_path, :string, 7
      optional :library, :string, 8
      optional :ref_unit, :string, 9
      optional :location, :string, 10
      optional :flow_type, :enum, 11, "protolca.ProtoFlowType"
      optional :process_type, :enum, 12, "protolca.ProtoProcessType"
    end
    add_message "protolca.ProtoSimpleResult" do
      repeated :flow_results, :message, 1, "protolca.ProtoFlowResult"
      repeated :impact_results, :message, 2, "protolca.ProtoImpactResult"
    end
    add_message "protolca.ProtoSocialAspect" do
      optional :activity_value, :double, 1
      optional :comment, :string, 2
      optional :quality, :string, 3
      optional :raw_amount, :string, 4
      optional :risk_level, :enum, 5, "protolca.ProtoRiskLevel"
      optional :social_indicator, :message, 6, "protolca.ProtoRef"
      optional :source, :message, 7, "protolca.ProtoRef"
    end
    add_message "protolca.ProtoSocialIndicator" do
      optional :id, :string, 1, json_name: "@id"
      optional :name, :string, 2
      optional :description, :string, 3
      optional :version, :string, 4
      optional :last_change, :string, 5
      optional :type, :enum, 6, "protolca.ProtoType", json_name: "@type"
      optional :category, :message, 7, "protolca.ProtoRef"
      repeated :tags, :string, 8
      optional :library, :string, 9
      optional :activity_variable, :string, 10
      optional :activity_quantity, :message, 11, "protolca.ProtoRef"
      optional :activity_unit, :message, 12, "protolca.ProtoRef"
      optional :unit_of_measurement, :string, 13
      optional :evaluation_scheme, :string, 14
    end
    add_message "protolca.ProtoSource" do
      optional :id, :string, 1, json_name: "@id"
      optional :name, :string, 2
      optional :description, :string, 3
      optional :version, :string, 4
      optional :last_change, :string, 5
      optional :type, :enum, 6, "protolca.ProtoType", json_name: "@type"
      optional :category, :message, 7, "protolca.ProtoRef"
      repeated :tags, :string, 8
      optional :library, :string, 9
      optional :url, :string, 10
      optional :text_reference, :string, 11
      optional :year, :int32, 12
      optional :external_file, :string, 13
    end
    add_message "protolca.ProtoUncertainty" do
      optional :distribution_type, :enum, 1, "protolca.ProtoUncertaintyType"
      optional :mean, :double, 2
      optional :mean_formula, :string, 3
      optional :geom_mean, :double, 4
      optional :geom_mean_formula, :string, 5
      optional :minimum, :double, 6
      optional :minimum_formula, :string, 7
      optional :sd, :double, 8
      optional :sd_formula, :string, 9
      optional :geom_sd, :double, 10
      optional :geom_sd_formula, :string, 11
      optional :mode, :double, 12
      optional :mode_formula, :string, 13
      optional :maximum, :double, 14
      optional :maximum_formula, :string, 15
    end
    add_message "protolca.ProtoUnit" do
      optional :id, :string, 1, json_name: "@id"
      optional :name, :string, 2
      optional :description, :string, 3
      optional :version, :string, 4
      optional :last_change, :string, 5
      optional :conversion_factor, :double, 6
      optional :reference_unit, :bool, 7
      repeated :synonyms, :string, 8
    end
    add_message "protolca.ProtoUnitGroup" do
      optional :id, :string, 1, json_name: "@id"
      optional :name, :string, 2
      optional :description, :string, 3
      optional :version, :string, 4
      optional :last_change, :string, 5
      optional :type, :enum, 6, "protolca.ProtoType", json_name: "@type"
      optional :category, :message, 7, "protolca.ProtoRef"
      repeated :tags, :string, 8
      optional :library, :string, 9
      optional :default_flow_property, :message, 10, "protolca.ProtoRef"
      repeated :units, :message, 11, "protolca.ProtoUnit"
    end
    add_enum "protolca.ProtoAllocationType" do
      value :UNDEFINED_ALLOCATION_TYPE, 0
      value :PHYSICAL_ALLOCATION, 1
      value :ECONOMIC_ALLOCATION, 2
      value :CAUSAL_ALLOCATION, 3
      value :USE_DEFAULT_ALLOCATION, 4
      value :NO_ALLOCATION, 5
    end
    add_enum "protolca.ProtoCalculationType" do
      value :UNDEFINED_CALCULATION_TYPE, 0
      value :SIMPLE_CALCULATION, 1
      value :CONTRIBUTION_ANALYSIS, 2
      value :UPSTREAM_ANALYSIS, 3
      value :MONTE_CARLO_SIMULATION, 4
    end
    add_enum "protolca.ProtoFlowPropertyType" do
      value :UNDEFINED_FLOW_PROPERTY_TYPE, 0
      value :ECONOMIC_QUANTITY, 1
      value :PHYSICAL_QUANTITY, 2
    end
    add_enum "protolca.ProtoFlowType" do
      value :UNDEFINED_FLOW_TYPE, 0
      value :ELEMENTARY_FLOW, 1
      value :PRODUCT_FLOW, 2
      value :WASTE_FLOW, 3
    end
    add_enum "protolca.ProtoParameterScope" do
      value :UNDEFINED_PARAMETER_SCOPE, 0
      value :PROCESS_SCOPE, 1
      value :IMPACT_SCOPE, 2
      value :GLOBAL_SCOPE, 3
    end
    add_enum "protolca.ProtoProcessType" do
      value :UNDEFINED_PROCESS_TYPE, 0
      value :LCI_RESULT, 1
      value :UNIT_PROCESS, 2
    end
    add_enum "protolca.ProtoRiskLevel" do
      value :UNDEFINED_RISK_LEVEL, 0
      value :NO_OPPORTUNITY, 1
      value :HIGH_OPPORTUNITY, 2
      value :MEDIUM_OPPORTUNITY, 3
      value :LOW_OPPORTUNITY, 4
      value :NO_RISK, 5
      value :VERY_LOW_RISK, 6
      value :LOW_RISK, 7
      value :MEDIUM_RISK, 8
      value :HIGH_RISK, 9
      value :VERY_HIGH_RISK, 10
      value :NO_DATA, 11
      value :NOT_APPLICABLE, 12
    end
    add_enum "protolca.ProtoUncertaintyType" do
      value :UNDEFINED_UNCERTAINTY_TYPE, 0
      value :LOG_NORMAL_DISTRIBUTION, 1
      value :NORMAL_DISTRIBUTION, 2
      value :TRIANGLE_DISTRIBUTION, 3
      value :UNIFORM_DISTRIBUTION, 4
    end
    add_enum "protolca.ProtoCategoryType" do
      value :UNDEFINED_CATEGORY_TYPE, 0
      value :ACTOR, 1
      value :CURRENCY, 3
      value :DQ_SYSTEM, 4
      value :FLOW, 5
      value :FLOW_PROPERTY, 6
      value :IMPACT_CATEGORY, 7
      value :IMPACT_METHOD, 8
      value :LOCATION, 9
      value :PARAMETER, 11
      value :PROCESS, 12
      value :PRODUCT_SYSTEM, 13
      value :PROJECT, 14
      value :SOCIAL_INDICATOR, 15
      value :SOURCE, 16
      value :UNIT_GROUP, 18
      value :RESULT, 19
    end
    add_enum "protolca.ProtoType" do
      value :Undefined, 0
      value :Actor, 1
      value :Category, 2
      value :Currency, 3
      value :DQSystem, 4
      value :Flow, 5
      value :FlowProperty, 6
      value :ImpactCategory, 7
      value :ImpactMethod, 8
      value :Location, 9
      value :NwSet, 10
      value :Parameter, 11
      value :Process, 12
      value :ProductSystem, 13
      value :Project, 14
      value :Result, 15
      value :SocialIndicator, 16
      value :Source, 17
      value :Unit, 18
      value :UnitGroup, 19
    end
  end
end

module Protolca
  ProtoActor = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoActor").msgclass
  ProtoAllocationFactor = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoAllocationFactor").msgclass
  ProtoCalculationSetup = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoCalculationSetup").msgclass
  ProtoCategory = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoCategory").msgclass
  ProtoCurrency = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoCurrency").msgclass
  ProtoDQIndicator = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoDQIndicator").msgclass
  ProtoDQScore = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoDQScore").msgclass
  ProtoDQSystem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoDQSystem").msgclass
  ProtoExchange = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoExchange").msgclass
  ProtoExchangeRef = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoExchangeRef").msgclass
  ProtoFlow = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoFlow").msgclass
  ProtoFlowMap = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoFlowMap").msgclass
  ProtoFlowMapEntry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoFlowMapEntry").msgclass
  ProtoFlowMapRef = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoFlowMapRef").msgclass
  ProtoFlowProperty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoFlowProperty").msgclass
  ProtoFlowPropertyFactor = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoFlowPropertyFactor").msgclass
  ProtoFlowResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoFlowResult").msgclass
  ProtoImpactCategory = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoImpactCategory").msgclass
  ProtoImpactFactor = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoImpactFactor").msgclass
  ProtoImpactMethod = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoImpactMethod").msgclass
  ProtoImpactResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoImpactResult").msgclass
  ProtoLocation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoLocation").msgclass
  ProtoNwFactor = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoNwFactor").msgclass
  ProtoNwSet = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoNwSet").msgclass
  ProtoParameter = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoParameter").msgclass
  ProtoParameterRedef = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoParameterRedef").msgclass
  ProtoParameterRedefSet = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoParameterRedefSet").msgclass
  ProtoProcess = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoProcess").msgclass
  ProtoProcessDocumentation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoProcessDocumentation").msgclass
  ProtoProcessLink = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoProcessLink").msgclass
  ProtoProductSystem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoProductSystem").msgclass
  ProtoProject = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoProject").msgclass
  ProtoRef = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoRef").msgclass
  ProtoSimpleResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoSimpleResult").msgclass
  ProtoSocialAspect = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoSocialAspect").msgclass
  ProtoSocialIndicator = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoSocialIndicator").msgclass
  ProtoSource = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoSource").msgclass
  ProtoUncertainty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoUncertainty").msgclass
  ProtoUnit = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoUnit").msgclass
  ProtoUnitGroup = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoUnitGroup").msgclass
  ProtoAllocationType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoAllocationType").enummodule
  ProtoCalculationType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoCalculationType").enummodule
  ProtoFlowPropertyType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoFlowPropertyType").enummodule
  ProtoFlowType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoFlowType").enummodule
  ProtoParameterScope = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoParameterScope").enummodule
  ProtoProcessType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoProcessType").enummodule
  ProtoRiskLevel = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoRiskLevel").enummodule
  ProtoUncertaintyType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoUncertaintyType").enummodule
  ProtoCategoryType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoCategoryType").enummodule
  ProtoType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protolca.ProtoType").enummodule
end
